### ISSUE TITLE
Handshake failed. Your blog does not support https, Try to changing it to http

### ISSUE THREAD

**Issue by tareefdev** [vickychijwani/quill#168] opened 2017-08-18 13:57 UTC
FILL THESE DETAILS FIRST:

- Ghost version: 1.5.2
- App version: 1.5.6

----
When I try to sing in with the app I got this message:

`Handshake failed. Your blog does not support https, Try to changing it to http!`

but if you open my blog:

blog.tareef.me

your can see that it run with SSL without any problem. How I can figure out the problem and solve it?

thanks

**Comment by vickychijwani** [comment] 2017-08-19 00:11
Hi @tareefdev 👋 

The Ghost 1.x support in Quill is in beta right now. To get it, you'll need to *opt in* to the beta here: https://play.google.com/apps/testing/me.vickychijwani.spectre.

Just follow the instructions there and you should be able to sign in. To confirm you have the beta installed, check your system settings > Apps > Quill. The version should be `2.0.0-beta2`.

I guess the error message could be clearer though (something like "Your blog uses Ghost 1.x. To use Quill with it, please opt in to the beta here: <link>). Let me see if I can do that - leaving this issue open to track.

**Comment by tareefdev** [comment] 2017-08-19 07:29
Hi @vickychijwani 

Thanks for your working in this wonderful app. I upgraded successfully to `2.0.0-beta2` (which use a new UI?), clean the app cache, but still face the same error!

What else can we do?

thanks :)

**Comment by vickychijwani** [comment] 2017-08-19 15:43
Let me guess: you're using Android 7.0 right? In that case I think I know what the problem is and can replicate it. The bad news is that it's a bug in Android 7.0 ([here's the bug report](https://code.google.com/p/android/issues/detail?id=224438)), which was fixed in Android 7.1.1.

So here are the solutions I can think of:

- Update your device to Android 7.1.1
- If that's not possible, try setting this in your Nginx configuration, because prime256v1 (also known as "secp256r1" or "NIST P-256") is the only elliptic curve Android 7.0 supports (that _is_ the bug): `ssl_ecdh_curve prime256v1;`
- If that doesn't work either, you may want to remove the elliptic-curve cipher suites (ones starting with "ECDHE") entirely from your Nginx configuration (depending on whether you think the security trade-off is worth it).

Let me know what works for you.

**Comment by tareefdev** [comment] 2017-08-19 17:35
You are right! My phone (Samsung S8) run with Android 7.0, But I think Samsung will send the version 7.1.1 this month or something like that.. so I prefer to wait this period of time although I'm very excited to try your app since it has a very nice reputation in the store

Big thanks for your help :)

**Comment by vickychijwani** [comment] 2017-08-26 15:14
Quill v2.0.0 is now rolled out to all users, so this issue can be closed 🎉

**Closed by vickychijwani** 2017-08-26 15:14 UTC
Labels: user feedback
